### ISSUE TITLE
[DATA] Divine Protection skill is right for Cleric but wrong for Paladin

### ISSUE THREAD

**Issue by jptettamanti** [DungeonPaper/dungeon_world_data#5]
There are two different versions of Divine Protection, one for the Cleric and one for the Paladin.
* The Cleric's move description is "When you wear no armor or shield you get 2 armor" and is correct.
* The Paladin's move description should be "You get +2 armor while on a quest"

**Comment by chenasraf** [comment]
Are you maybe talking about Divine Protection? I see no Divine Armor for Paladin in the SRD. (Sorry about the long delay)

https://www.dungeonworldsrd.com/classes/paladin/#Divine_Protection
