### ISSUE TITLE
[BUG] Wizard has the cleric "Cast a spell" move.

### ISSUE THREAD

**Issue by magnus-ISU** [DungeonPaper/dungeon_world_data#9]
**Describe the bug**

**To Reproduce**
2. Tap on '....'
3. See error

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2 XL]
 - OS: [e.g. Android 10]
 - Version [e.g. 1.0.15]

**Additional context**

**Comment by chenasraf** [comment]
Fixed in v3.0.3 ([b08a3a2](https://github.com/DungeonPaper/dungeon_world_data/commit/b08a3a2d14cf7b4f25adc32f22114a7b97de9619))  and v3.0.4 ([50c8012](https://github.com/DungeonPaper/dungeon_world_data/commit/50c8012df09f92dd3b0215766b0a7648bf64d999))
